# title: Data Nodes per Species
# category: Metadata
# description: Counts the number of distinct data nodes per species in WikiPathways,
#   ordered by count descending.

select (count(distinct ?datanode) as ?count) (str(?label) as ?species) where {
  ?datanode a wp:DataNode ;
    dcterms:isPartOf ?pw .
  ?pw dc:title ?title ;
    wp:organism ?organism ;
    wp:organismName ?label .
} GROUP BY ?label ORDER BY DESC(?count)
