PREFIX : <http://nextprot.org/rdf#>
select distinct  ?pathwayname ?entry str(?gen)  (group_concat(distinct str(?loclab); SEPARATOR = ",") as ?locations) where {
  {?geneProduct a wp:Protein}
   union
  {?geneProduct a wp:GeneProduct}
  ?geneProduct rdfs:label ?gen .
  filter(!regex(?gen,"[ a-z-]")).
  ?geneProduct dcterms:isPartOf ?pathway .
  ?pathway a wp:Pathway .
  ?pathway wp:organism ?organism .
  filter(contains(str(?organism),"9606")) 
  ?pathway dc:title ?pathwayname .
  filter(regex(?pathwayname,"Rett")).
  service <https://api.nextprot.org/sparql> {
    ?entry a :Entry ;
     :gene / :name ?gen ;
     :isoform ?iso.
    ?iso :cellularComponent ?locannot .
    ?locannot :term ?locterm .
    ?locterm rdfs:label ?loclab .
    ?locannot :evidence ?locev .
    ?locev :quality :GOLD .
  }}
order by ?pathwayname
