PREFIX wp: <http://vocabularies.wikipathways.org/wp#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX cur: <http://vocabularies.wikipathways.org/wp#Curation:>

SELECT DISTINCT ?pathway (str(?title) as ?PathwayTitle)
WHERE {
  ?pathway wp:ontologyTag cur:AOP ; 
  a wp:Pathway ; 
  dc:title ?title .
}