SELECT DISTINCT ?wpIdentifier ?pathway ?title ?page
WHERE {
    ?pathway dc:title ?title ;
       foaf:page ?page ;
       dc:identifier ?wpIdentifier ;
       wp:organismName "Mus musculus" .
 }
ORDER BY ?wpIdentifier
