PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX wpq:   <http://www.wikidata.org/prop/qualifier/>
PREFIX pav:   <http://purl.org/pav/>

SELECT ?pathway ?version ?ordinal ?author_ ?name ?orcid ?page WHERE {
  VALUES ?pathway { <https://identifiers.org/wikipathways/WP4846> }
  ?author_ a foaf:Person ;
    wp:hasAuthorship ?authorship .
  ?authorship ^wp:hasAuthorship ?pathway ;
    wpq:series_ordinal ?ordinal .
  ?pathway a wp:Pathway ; pav:hasVersion / wp:isAbout / gpml:version ?version .
  OPTIONAL { ?author_ foaf:homepage ?page }
  OPTIONAL { ?author_ foaf:name ?name }
  OPTIONAL { ?author_ dc:identifier ?orcid }
} ORDER BY ASC(?pathway) ASC(?ordinal)
