# title: First Authors of Pathways
# category: Authors
# description: Lists the first author (ordinal 1) of each pathway, ordered by
#   pathway version number.

PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX wpq:   <http://www.wikidata.org/prop/qualifier/>
PREFIX pav:   <http://purl.org/pav/>

SELECT ?pathway ?version ?ordinal ?name ?orcid ?page WHERE {
  VALUES ?ordinal { "1" }
  ?author_ a foaf:Person ;
    wp:hasAuthorship ?authorship .
  ?authorship ^wp:hasAuthorship ?pathway ;
    wpq:series_ordinal ?ordinal .
  ?pathway pav:hasVersion ?pathway_ .
  ?pathway_ a wp:Pathway ; dcterms:identifier ?version .
  OPTIONAL { ?author_ foaf:homepage ?page }
  OPTIONAL { ?author_ foaf:name ?name }
  OPTIONAL { ?author_ dc:identifier ?orcid }
} ORDER BY ASC(xsd:integer(SUBSTR(str(?version),3))) ASC(?ordinal)
