# title: Metabolites of a Pathway
# category: General
# description: Lists all metabolites in a given pathway, returning the pathway
#   identifier and metabolite labels.
# param: pathwayId | string | WP1560 | Pathway ID

select distinct ?pathway (str(?label) as ?Metabolite) where {
    ?Metabolite a wp:Metabolite ;
       rdfs:label ?label ;
       dcterms:isPartOf ?pathway .
    ?pathway a wp:Pathway ;
    dcterms:identifier "{{pathwayId}}" .
}
