# title: Metabolites of a Pathway
# category: General
# description: Lists all metabolites in a given pathway, returning the pathway
#   identifier and metabolite labels.
# param: pathwayId|autocomplete:pathway|WP1560|Pathway ID

select distinct ?pathway (str(?label) as ?Metabolite) where {
    {
        SELECT ?pathway WHERE {
            ?pathway dcterms:identifier "{{pathwayId}}" .
            ?pathway a wp:Pathway .
        }
    }
    ?Metabolite a wp:Metabolite ;
       rdfs:label ?label ;
       dcterms:isPartOf ?pathway .
}
