# title: Dataset Metadata
# category: Metadata
# description: Returns all VoID datasets in the WikiPathways RDF with their title,
#   creation date, and license information.

SELECT DISTINCT ?dataset (str(?titleLit) as ?title) ?date ?license 
WHERE {
   ?dataset a void:Dataset ;
   dcterms:title ?titleLit ;
   dcterms:license ?license ;
   pav:createdOn ?date .
}