PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?prefix ?namespace WHERE {
  [] sh:declare [
    sh:prefix ?prefix ;
    sh:namespace ?namespace
  ] .
}