### Part 1: ###
SELECT DISTINCT ?interaction ?sourceDb ?targetDb ?PWOnt ?DiseaseOnt 
?curationstatus ?InteractionRef ?PWref ?sourceLit ?targetLit 
WHERE {
?pathway a wp:Pathway ; 
         	wp:organismName "Homo sapiens"; 
         	dc:title ?titleLit . 
?interaction dcterms:isPartOf ?pathway ; 
   a wp:DirectedInteraction ; 
   wp:source ?source ;
   wp:target ?target . 
?source a wp:Metabolite . 
?source wp:bdbWikidata ?sourceDb . 
?target a wp:Metabolite . 
?target wp:bdbWikidata ?targetDb . 

### Part 2: ###
#OPTIONAL{?pathway wp:pathwayOntologyTag ?PWOnt} . 
#OPTIONAL{?pathway wp:diseaseOntologyTag ?DiseaseOnt} . 

### Part 3: ###
#OPTIONAL{?pathway wp:ontologyTag ?curationstatus} . 

### Part 4: ###
OPTIONAL{?interaction dcterms:bibliographicCitation ?InteractionRef} . 
OPTIONAL{?pathway dcterms:references ?PWref} . 
OPTIONAL{?source dcterms:bibliographicCitation ?sourceLit} . 
OPTIONAL{?target dcterms:bibliographicCitation ?targetLit} . 
}
