PREFIX ro: <http://purl.obolibrary.org/obo/RO_>

SELECT ?bgc ?gene
FROM <http://plantmetwiki.bioinformatics.nl/>
WHERE {
  ?bgc ro:0000051 ?gene .
  FILTER(STRSTARTS(STR(?bgc), "https://bioregistry.io/mibig:"))
}
ORDER BY ?bgc ?gene
LIMIT 200