PREFIX ro: <http://purl.obolibrary.org/obo/RO_>
PREFIX wp:  <http://vocabularies.wikipathways.org/wp#>
PREFIX dc:  <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>

# Retrieve thalianol pathway 
SELECT DISTINCT ?pw (STR(?titleLit) AS ?title)
FROM <http://plantmetwiki.bioinformatics.nl/>
WHERE {
  <https://bioregistry.io/mibig:BGC0000670> ro:0000051 ?gene .

  ?interaction wp:participants ?gene ;
              dcterms:isPartOf ?pw .

  ?pw dc:title ?titleLit .
}
ORDER BY ?title