# title: References in Reactome but Not WikiPathways
# category: Communities
# description: Counts publication references found in Reactome-approved pathways but not
#   in the WikiPathways Analysis Collection.

SELECT (COUNT(DISTINCT ?pubmed) AS ?count)
WHERE {
  ?pubmed a       wp:PublicationReference .
  MINUS { ?pubmed dcterms:isPartOf/wp:ontologyTag cur:AnalysisCollection }
  { ?pubmed dcterms:isPartOf/wp:ontologyTag cur:Reactome_Approved }
}
