SELECT DISTINCT ?pathway ?interaction ?pubmed ?partnerref WHERE {
   ?pathway a wp:Pathway ;
            dc:identifier <https://identifiers.org/wikipathways/WP5200> .
   ?interaction dcterms:isPartOf ?pathway ;
                a wp:Interaction ;
                wp:participants ?partner;
                dcterms:references ?pubmed .
   OPTIONAL{?partner dc:identifier ?partnerID ;
            dcterms:references ?partnerref .}
} LIMIT 100
