SELECT DISTINCT ?pathway ?interaction ?pubmed
WHERE {

   ?pathway a wp:Pathway ;
      dc:identifier <https://identifiers.org/wikipathways/WP5200> . #filter for one pathway
   ?interaction dcterms:isPartOf ?pathway ; 
      a wp:Interaction ;
       dcterms:references ?pubmed ;
      wp:participants ?participants .
   ?participants a wp:DataNode ;
      rdfs:label ?DataNodeLabel .  
}
