# title: Count of Pathways
# category: Metadata
# description: Counts the total number of pathways in WikiPathways.

SELECT DISTINCT count(?Pathway) as ?PathwayCount
WHERE {
    ?Pathway a wp:Pathway, skos:Collection .
} 
