prefix lipidmaps:      <https://identifiers.org/lipidmaps/> #IRI can be used to create URLs from identifiers in line 7
select distinct ?pathwayRes (str(?wpid) as ?pathway) (str(?title) as ?pathwayTitle) (count(distinct ?lipidID) AS ?LipidsInPWs)
where {
  ?metabolite a wp:Metabolite ;    #Define what are metabolites
    dcterms:identifier ?id ;       #Find the identifier of a certain metabolite
    dcterms:isPartOf ?pathwayRes ; #Define metabolites are part of a pathway
    wp:bdbLipidMaps ?lipidID .     #Find the LIPID MAPS identifier for a certain metabolite
  ?pathwayRes a wp:Pathway ;       #Define what is a pathway
              wp:organismName "Homo sapiens"^^xsd:string ; #Filter pathways on species Human
    dcterms:identifier ?wpid ;     #Obtain identifier of pathway
    dc:title ?title .              #Obtain title of pathway
}

ORDER BY DESC(?LipidsInPWs)
