# title: Lipids Count per Pathway
# category: Communities
# description: Counts the total number of lipids with LIPID MAPS identifiers per human
#   pathway, ordered by count.
# param: species | enum:Acetobacterium woodii,Anopheles gambiae,Arabidopsis thaliana,Bacillus subtilis,Beta vulgaris,Bos taurus,Brassica napus,Caenorhabditis elegans,Canis familiaris,Caulobacter vibrioides,Citrus sinensis,Coffea arabica,Danio rerio,Daphnia magna,Drosophila melanogaster,Equus caballus,Escherichia coli,Gallus gallus,Gibberella zeae,Homo sapiens,Hordeum vulgare,Ilex paraguariensis,Mus musculus,Mycobacterium tuberculosis,Oryza sativa,Pan troglodytes,Paullinia cupana,Perilla frutescens,Plasmodium falciparum,Populus trichocarpa,Rattus norvegicus,Saccharomyces cerevisiae,Solanum lycopersicum,Sus scrofa,Theobroma cacao,Triticum aestivum,Vitis vinifera,Zea mays | Homo sapiens | Species

prefix lipidmaps:      <https://identifiers.org/lipidmaps/> #IRI can be used to create URLs from identifiers in line 7
select distinct ?pathwayRes (str(?wpid) as ?pathway) (str(?title) as ?pathwayTitle) (count(distinct ?lipidID) AS ?LipidsInPWs)
where {
  ?metabolite a wp:Metabolite ;    #Define what are metabolites
    dcterms:identifier ?id ;       #Find the identifier of a certain metabolite
    dcterms:isPartOf ?pathwayRes ; #Define metabolites are part of a pathway
    wp:bdbLipidMaps ?lipidID .     #Find the LIPID MAPS identifier for a certain metabolite
  ?pathwayRes a wp:Pathway ;       #Define what is a pathway
              wp:organismName "{{species}}" ; #Filter pathways on species Human
    dcterms:identifier ?wpid ;     #Obtain identifier of pathway
    dc:title ?title .              #Obtain title of pathway
}

ORDER BY DESC(?LipidsInPWs)
