# title: Inborn Errors of Metabolism Pathways
# category: Communities
# description: Lists all pathways tagged with the Inborn Errors of Metabolism (IEM) community curation tag.

SELECT DISTINCT ?pathway (str(?title) as ?PathwayTitle)
WHERE {
?pathway wp:ontologyTag cur:IEM ; 
a wp:Pathway ; 
dc:title ?title .}
